version: '3.8'
services:
  fooocus_rocmyai561:
    image: devloic/fooocus_rocmyai-5.6.1
    container_name: fooocus_rocmyai561
    volumes:
      - ./mymodels:/home/ai/Fooocus/models
      #- /mnt/ext4ssd/fooocus/models:/home/ai/Fooocus/models
    command: bash
    ports:
      - 7860
    group_add:
      - $RENDER_ID
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
